### ISSUE TITLE
/encoding crashes

### ISSUE THREAD

**Issue by desaster** [desaster/epic5-bugs#3]
using an existing channel, the following commands in a sequence cause a crash:

```
/encoding #channel ISO-8859-1
/encoding #channel NONE
```

Info:

```
Command line:

epic5 -q testasdasd irc.freenode.net -c \#epic5-testing

Commit ID: e76e9a1447338c97ae0efa22210e66812f627d9d

/encoding
*** [0] Encoding for console is UTF-8 : (From locale)
*** [1] Encoding for scripts is CP437 : (Default value)
*** [2] Encoding for irc is ISO-8859-1 : (Default value)

$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

gdb:

```
Program received signal SIGSEGV, Segmentation fault.
__gconv_close (cd=0x0) at gconv_close.c:35
35      gconv_close.c: No such file or directory.
(gdb) bt
#0  __gconv_close (cd=0x0) at gconv_close.c:35
#1  0x00007ffff6f7555f in iconv_close (cd=<optimized out>) at iconv_close.c:35
#2  0x00000000004a4b3f in encoding (command=0x7b0ac8 "ENCODING", args=0x7b0ae4 "", subargs=0x0)
    at recode.c:1123
#3  0x0000000000438f25 in parse_statement (stmt=0x7fffffffc241 "encoding #epic5-testing NONE",
    interactive=1, subargs=0x0) at commands.c:3953
#4  0x0000000000473eca in send_line (key=10, string=0x0) at input.c:1547
#5  0x00000000004828b0 in key_exec (key=0x768a68) at keys.c:434
#6  0x0000000000482bea in handle_keypress (lastp=0x0, pressed=..., keyx=10, quote_override=0)
    at keys.c:656
#7  0x00000000004ace4e in edit_codepoint (key=10) at screen.c:3841
#8  0x00000000004acd6e in translate_user_input (byte=10 '\n') at screen.c:3786
#9  0x00000000004aca48 in do_screens (fd=0) at screen.c:3661
#10 0x00000000004932bb in do_filedesc () at newio.c:477
#11 0x0000000000475870 in io (what=0x4e78c0 "main") at ./irc.c:939
#12 0x0000000000475db4 in main (argc=6, argv=0x7fffffffe5b8) at ./irc.c:1299
(gdb)

```

**Comment by nhockey** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff51f0831 in __gconv_close () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff51f0831 in __gconv_close () from /usr/lib/libc.so.6
#1  0x00007ffff51f011f in iconv_close () from /usr/lib/libc.so.6
#2  0x00000000004b0137 in encoding (command=0x8ab7e8 "ENCODING", args=0x8ab7fe "", subargs=0x0) at recode.c:1123
#3  0x0000000000428730 in parse_statement (stmt=0x7fffffffbd21 "encoding #channel NONE", interactive=1, subargs=0x0) at commands.c:3953
#4  0x00000000004781fa in send_line (key=10, string=0x0) at input.c:1547
#5  0x000000000048b4e6 in key_exec (key=0x7a4c38) at keys.c:434
#6  0x000000000048b12c in handle_keypress (lastp=0x0, pressed=..., keyx=10, quote_override=0) at keys.c:656
#7  0x00000000004ba9bd in edit_codepoint (key=10) at screen.c:3841
#8  0x00000000004ba8b9 in translate_user_input (byte=10 '\n') at screen.c:3786
#9  0x00000000004b93c9 in do_screens (fd=0) at screen.c:3661
#10 0x00000000004a0bad in do_filedesc () at newio.c:477
#11 0x0000000000478ec4 in io (what=0x500733 "main") at ./irc.c:939
#12 0x00000000004796c3 in main (argc=1, argv=0x7fffffffe278) at ./irc.c:1299
```

**Comment by desaster** [comment]
fixed in 1828
